### PR TITLE
#18 Added depth option

### PR DESCRIPTION
**Pull request by oriefrati**
this changes allow future options and allow to configure depth #18

### CODE REVIEW

**Comment by OriTheMan** [comment]
I don't know why it fail in travic-ci in my local machine everything passed

```
$ ./node_modules/.bin/istanbul cover ./node_modules/.bin/jest && ./node_modules/.bin/codecov
 PASS  __test__/dumper.test.js
  Dump class tests
    ✓ can dump strings (5ms)
    ✓ can dump boolean values
    ✓ can dump numeric values (2ms)
    ✓ can dump regex values
    ✓ can dump function values inside object (1ms)
    ✓ can dump null values
    ✓ can dump undefined values (1ms)
    ✓ can dump array values
    ✓ can dump object values
    ✓ can dump cycled object (1ms)
    ✓ can dump object without hasOwnProperty
    ✓ dump with depth 1 (1ms)
    ✓ dump with depth 2
    ✓ dump with depth 3

Test Suites: 1 passed, 1 total
Tests:       14 passed, 14 total

```

**Comment by Oxicode** [comment]
:0

**Comment by Oxicode** [comment]
+1

**Comment by Oxicode** [comment]
@ziishaned

**Pull request closed without merging**
